[package]
name = "hello"
version = "2.12.1"
revision = 1
architecture = "x86_64"
summary = "GNU Hello World program"
license = "GPL-3.0-or-later"
homepage = "https://www.gnu.org/software/hello/"
depends = []

[source]
url = "https://ftp.gnu.org/gnu/hello/hello-2.12.1.tar.gz"
sha256 = "8d99142afd92576f30b0cd7cb42a8dc6809998bc5d607d88761f512e26c7db20"

[build]
script = """
./configure --prefix=/usr
make -j$(nproc)
make DESTDIR="${DESTDIR}" install
"""
