[package]
name = "aqj-src"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
aqj-core = { path = "../aqj-core" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tar.workspace = true
flate2.workspace = true
zstd.workspace = true
ureq.workspace = true
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
